repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-json
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/psf/black
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    hooks:
      - id: isort
  - repo: https://github.com/humitos/mirrors-autoflake.git
    hooks:
      - id: autoflake
  - repo: https://github.com/pre-commit/mirrors-mypy
    hooks:
      - id: mypy
