contact_links:
  - name: Project management board
    url: https://github.com/Vexed01/Vex-Cogs/projects/1
    about: Before you open an issue, please check it's not already on this board. Some stuff is **ONLY on there and is not open as an issue.**
