name: Auto tag

on: push

jobs:
  style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    name: Auto tag
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        pip install gitpython

    - name: Set up git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: Run script autotag.py
      run: |
        python .github/workflows/scripts/autotag.py
